### ISSUE TITLE
Landing Page [Map]

### ISSUE THREAD

**Issue by skyuplam** [impact-learning/frontend-demo#1]
# Features

- [x] World Map as base layer, will be using openstreet map (osm.org)
- [x] China on the center with province borders
- [x] Project viz on map #5
- [x] Able to Zoom in and out
- [x] Timeline #6
- [x] Data Selection tool to choose the Economic, Environment and Social Impact #7

# Structure 
- [x] OCM Layer
- [x] Country Borders Layer
- [x] Province Layer
- [x] Circle Layer for showing the indexes of the project #5
- [x] Timeline Layer #6
- [x] Data model (w/ filter) #7

**Comment by skyuplam** [comment]
- OCM Layer
- Country Borders Layer
- Province Layer
- Heatmap Layer for the villages
- Timeline Layer
- Data model (w/ filter)

**Comment by skyuplam** [comment]
#4
